#pragma once

enum USBV0IOCtl
{
  USBV0_IOCTL_CTRLMSG = 0,
  USBV0_IOCTL_BLKMSG = 1,
  USBV0_IOCTL_INTRMSG = 2,
  USBV0_IOCTL_SUSPENDDEV = 5,
  USBV0_IOCTL_RESUMEDEV = 6,
  USBV0_IOCTL_ISOMSG = 9,
  USBV0_IOCTL_GETDEVLIST = 12,
  USBV0_IOCTL_DEVREMOVALHOOK = 26,
  USBV0_IOCTL_DEVINSERTHOOK = 27,
  USBV0_IOCTL_DEVICECLASSCHANGE = 28,
};

enum USBV5IOCtl
{
  USBV5_IOCTL_GETVERSION = 0,
  USBV5_IOCTL_GETDEVICECHANGE = 1,
  USBV5_IOCTL_SHUTDOWN = 2,
  USBV5_IOCTL_GETDEVPARAMS = 3,
  USBV5_IOCTL_ATTACHFINISH = 6,
  USBV5_IOCTL_SETALTERNATE = 7,
  USBV5_IOCTL_SUSPEND_RESUME = 16,
  USBV5_IOCTL_CANCELENDPOINT = 17,
  // IOCtlVs
  USBV5_IOCTL_CTRLMSG = 18,
  USBV5_IOCTL_INTRMSG = 19,
  USBV5_IOCTL_ISOMSG = 20,
  USBV5_IOCTL_BULKMSG = 21
};
